### PR TITLE
Restructure

### LINKED ISSUE #15: Restructure files

### PR DESCRIPTION
**Pull request by jacobchh**
Resolves #15 
Ability to split views.py into different files in the future

### CODE REVIEW

**Review by jerryxu99 — COMMENTED** [review]
Discussed thoroughly over messenger. Note for Varun, often in python we found that views is synonymous with controller. 

@varun-patel any thoughts?

**Comment by varun-patel** [comment]
> Discussed thoroughly over messenger. Note for Varun, often in python we found that views is synonymous with controller.

This may be the case for static web pages being served, in our case, as we are handling JSON, we don't need traditional HTML views and you can treat a 'view' as the json object the controller returns.

_basically my recommendation is to put your views inside your controller_

In the end it's up to all of you @luscinia-enterprises/api to figure it out.

**Comment by jacobchh** [comment]
Most Flask apps will name them views because they're "like" HTML views in that they all have different endpoints/links. Each endpoint is defined with the possible interactions with the api. @varun-patel

**Comment by varun-patel** [comment]
> Most Flask apps will name them views because they're "like" HTML views in that they all have different endpoints/links. Each endpoint is defined with the possible interactions with the api.

In my experience, view implies templating language and dynamic resolution. You can look through [https://pythonhosted.org/Flask-Views/index.html](https://pythonhosted.org/Flask-Views/index.html). In the end it's your call.

**Comment by varun-patel** [comment]
also do you need a review from me?

**Comment by jerryxu99** [comment]
no need for you to review I can do that

**Comment by jacobchh** [comment]
In my experience, views referred to dynamic renders as well. We could name it endpoints, that would be a more accurate description. @varun-patel

**Comment by jacobchh** [comment]
renamed to endpoints.py to refer to api endpoints @varun-patel @jerryxu99

**Comment by jerryxu99** [comment]
Can we rename controller to views then? I think that's more common than controller.

**Comment by jacobchh** [comment]
Sounds good to me @jerryxu99

**Review by jerryxu99 — APPROVED** [review]
Nevermind, we talked on messenger we'll keep it this way.

**Comment by varun-patel** [comment]
You're free to squash and merge whenever you're ready

**Pull request merged**
