### PR TITLE
Token authentication

### LINKED ISSUE #3: Token-Based Authentication
Work with Redis database and enable token-based authentication using internally developed token auth standards.

### PR DESCRIPTION
**Pull request by DevenMarrero**
Test code is left in for future reference

### CODE REVIEW

**Comment by varun-patel** [comment]
@DevenMarrero please resolve the CodeFactor check failure before continuing.

**Review by jerryxu99 — CHANGES_REQUESTED** [review]
The code is looking very clean, love the comments!
Just quickly fix up the extra space outlined in the CodeFactor review and then should be good to merge

**Comment by varun-patel** [comment]
> The code is looking very clean, love the comments!
> Just quickly fix up the extra space outlined in the CodeFactor review and then should be good to merge

also just need the docker ci to pass, but you wont be able to merge until all the important checks pass

**Review by jerryxu99 — APPROVED** [review]
looks great feel free to squash and merge

**Pull request merged**
